# Generated by Django 5.0.1 on 2024-05-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click the link above to read more about this blog', max_length=255),
        ),
    ]
